INSERT INTO BREWERY (ID, NAME, LOCATION)
VALUES (random_uuid(), 'Guinness', 'St. James''s Gate, Dublin 8, Ireland'),
       (random_uuid(), 'Erdinger Weissbrau', '1-20 Franz-Brombach St., Erding, Germany'),
       (random_uuid(), 'Carlsberg', 'Vesterbro, Copenhagen, Denmark'),
       (random_uuid(), 'Kronenbourg', 'Strasbourg, France'),
       (random_uuid(), 'Smithwicks', 'Kilkenny, Ireland'),
       (random_uuid(), 'Heineken', 'Amsterdam, Netherlands'),
       (random_uuid(), 'Pilsner Urquell', 'Pilsen, Czech Republic'),
       (random_uuid(), 'Blue Moon Brewing Co', 'Denver, Colorado, USA');

INSERT INTO BEER (ID, NAME, DESCRIPTION, ALCOHOL_PERCENTAGE, BREWERY_ID)
VALUES (random_uuid(), 'Guinness Draught', 'Stout', 4.2, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Guinness Original', 'Stout', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Guinness West Indies', 'Porter', 6.0, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Guinness Rye Pale Ale', 'Pale Ale', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Hop House 13', 'Lager', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Guinness Golden Ale', 'Golden Ale', 4.5, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Dublin Porter', 'Porter', 3.8, (SELECT ID from BREWERY WHERE NAME = 'Guinness')),
       (random_uuid(), 'Erdinger Weissbier', 'Wheat Beer', 5.3, (SELECT ID from BREWERY WHERE NAME = 'Erdinger Weissbrau')),
       (random_uuid(), 'Erdinger Alkoholfrei', 'Alcohol free', 0.4, (SELECT ID from BREWERY WHERE NAME = 'Erdinger Weissbrau')),
       (random_uuid(), 'Erdinger Dunkel', 'Dark Wheat Beer', 5.3, (SELECT ID from BREWERY WHERE NAME = 'Erdinger Weissbrau')),
       (random_uuid(), 'Carlsberg Export', 'Pilsner', 4.8, (SELECT ID from BREWERY WHERE NAME = 'Carlsberg')),
       (random_uuid(), 'Carlsberg', 'European Pale Lager', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Carlsberg')),
       (random_uuid(), 'Carlsberg Citrus', 'Fruit Beer', 2.8, (SELECT ID from BREWERY WHERE NAME = 'Carlsberg')),
       (random_uuid(), 'Carlsberg Light', 'Pale Lager', 3.2, (SELECT ID from BREWERY WHERE NAME = 'Carlsberg')),
       (random_uuid(), 'Kronenbourg 1664', 'European Pale Lager', 4.5, (SELECT ID from BREWERY WHERE NAME = 'Kronenbourg')),
       (random_uuid(), 'Kronenbourg 1664 Blanc', 'Wheat Beer', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Kronenbourg')),
       (random_uuid(), 'Kronenbourg 1664 Fruits Rouge', 'Fruit Beer', 4.5, (SELECT ID from BREWERY WHERE NAME = 'Kronenbourg')),
       (random_uuid(), 'Smithwicks Red Ale', 'Red Ale', 4.5, (SELECT ID from BREWERY WHERE NAME = 'Smithwicks')),
       (random_uuid(), 'Smithwicks Pale Ale', 'Pale Ale', 4.5, (SELECT ID from BREWERY WHERE NAME = 'Smithwicks')),
       (random_uuid(), 'Smithwicks Blonde Ale', 'Blonde Ale', 4.1, (SELECT ID from BREWERY WHERE NAME = 'Smithwicks')),
       (random_uuid(), 'Heineken', 'Pale Lager', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Heineken')),
       (random_uuid(), 'Heineken Dark Lager', 'Dark Lager', 5.0, (SELECT ID from BREWERY WHERE NAME = 'Heineken')),
       (random_uuid(), 'Pilsner Urquell', 'Pilsner', 4.4, (SELECT ID from BREWERY WHERE NAME = 'Pilsner Urquell')),
       (random_uuid(), 'Gambrinus', 'Pilsner', 4.3, (SELECT ID from BREWERY WHERE NAME = 'Pilsner Urquell')),
       (random_uuid(), 'Blue Moon Belgian White', 'Wheat Beer', 5.4, (SELECT ID from BREWERY WHERE NAME = 'Blue Moon Brewing Co')),
       (random_uuid(), 'Blue Moon Mango Wheat', 'Wheat Beer', 5.4, (SELECT ID from BREWERY WHERE NAME = 'Blue Moon Brewing Co')),
       (random_uuid(), 'Blue Moon Summer Honey Wheat', 'Wheat Beer', 5.2, (SELECT ID from BREWERY WHERE NAME = 'Blue Moon Brewing Co'));
